### ISSUE TITLE
Added to julia package manager?

### ISSUE THREAD

**Issue by njwfish** [mpf/QRupdate.jl#6]
Hello!Thank you so much for creating the package! I find it super useful. It'd be great to see this added back to Julia's package manager and updated! It seems like the PR for Julia 1.5 works, so I don't think it would be too hard! If you no longer want to manage/maintain this, I would also be happy to take it on; it seems relatively low maintenance.

**Comment by mpf** [comment]
I just accepted the PR and registered the package. Thanks!
