### ISSUE TITLE
Implement in-place operations

### ISSUE THREAD

**Issue by mpf** [mpf/QRupdate.jl#8]
See [this commit](https://github.com/jekyllstein/QRupdate.jl/commit/6fdd94ebb0456a05f16e4d8b3ac9ecaa5b702d95) for pointers to operations that can be performed in place.

**Comment by nabw** [comment]
Hi, would you be willing to accept pull requests for this feature? It is an important missing feature in Julia I believe, and I would be willing to work on it.

**Comment by mpf** [comment]
Absolutely — I'll be glad to have this included.

**Comment by nabw** [comment]
Ok, I had some stuff coded from before. Please check this request whenever you can: https://github.com/mpf/QRupdate.jl/pull/10

Best!
